# Generated by Django 4.0.6 on 2022-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('ref', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crawling',
            name='search',
            field=models.CharField(max_length=10),
        ),
    ]
