# Generated by Django 4.0.6 on 2022-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_crawlingsubject_alter_crawling_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingsubject',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
